import { useEffect, useRef, useState } from "react";
import { request } from "../../lib/bridge";
import { errorMessage } from "../../lib/react";
import { useSystemSettings } from "../../lib/settings";
import { Toggle } from "../../components/Toggle";
import { SystemSlider } from "../../components/SystemSlider";
import type { DisplayOutput } from "../../lib/generated/DisplayOutput";
import type { DisplayConfig } from "../../lib/generated/DisplayConfig";
import type { DisplayTrial } from "../../lib/generated/DisplayTrial";
import type { WifiNetwork } from "../../lib/generated/WifiNetwork";
import type { BluetoothDevice } from "../../lib/generated/BluetoothDevice";

export function Displays() {
 const [outputs, setOutputs] = useState<DisplayOutput[]>([]), [edits, setEdits] = useState<DisplayConfig[]>([]), [selected, select] = useState(""), [busy,setBusy]=useState(false), [error,setError]=useState("");
 const [monitorBrightness,setMonitorBrightness]=useState<number|null>(null), [brightnessBusy,setBrightnessBusy]=useState(false);
 const brightnessTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [trial,setTrial]=useState<DisplayTrial|null>(null), [seconds,setSeconds]=useState(0);
 const {settings}=useSystemSettings();
 const report=(e:unknown)=>setError(errorMessage(e));
 async function load() { const result=await request({method:"settings.displays"}); setOutputs(result ?? []); setEdits((result ?? []).map(o=>{const m=o.current ?? o.modes.find(m=>m.preferred) ?? o.modes[0]; return { name:o.name,enabled:o.enabled,x:o.x,y:o.y,scale:o.scale,transform:o.transform,width:m?.width??0,height:m?.height??0,refresh:m?.refresh??0 };})); select(old=>result?.some(o=>o.name===old)?old:result?.[0]?.name??""); }
 useEffect(()=>{void load().catch(report);},[]);
 useEffect(()=>{if(brightnessTimer.current)clearTimeout(brightnessTimer.current);setMonitorBrightness(null);const output=outputs.find(o=>o.name===selected);if(!output||!output.enabled||output.name.startsWith("eDP")||output.name.startsWith("LVDS")||output.name.startsWith("DSI"))return;setBrightnessBusy(true);void request({method:"settings.monitor_brightness",params:{connector:output.name,percent:null}}).then(value=>setMonitorBrightness(value.percent)).catch(()=>setMonitorBrightness(null)).finally(()=>setBrightnessBusy(false));},[selected,outputs]);
 useEffect(()=>()=>{if(brightnessTimer.current)clearTimeout(brightnessTimer.current);},[]);
 function setExternalBrightness(percent:number){setMonitorBrightness(percent);if(brightnessTimer.current)clearTimeout(brightnessTimer.current);brightnessTimer.current=setTimeout(()=>{setBrightnessBusy(true);void request({method:"settings.monitor_brightness",params:{connector:selected,percent}}).catch(report).finally(()=>setBrightnessBusy(false));},250);}
 const trialRef=useRef(trial); trialRef.current=trial;
 async function decide(keep:boolean) { const current=trialRef.current; if(!current)return; setBusy(true);setError(""); try{await request({method:"settings.display_decide",params:{token:current.token,keep}});}catch(e){report(e);}finally{setTrial(null);await load().catch(report);setBusy(false);} }
 useEffect(()=>{if(!trial)return; const deadline=Date.now()+trial.seconds*1000; setSeconds(trial.seconds);const interval=setInterval(()=>{const remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));setSeconds(remaining);if(!remaining){clearInterval(interval);void decide(false);}},250); return ()=>clearInterval(interval);},[trial]);
 function update(patch:Partial<DisplayConfig>){setEdits(old=>old.map(o=>o.name===selected?{...o,...patch}:o));}
 async function apply(){setBusy(true);setError("");try{const value=await request({method:"settings.display_apply",params:{outputs:edits}});setTrial(value);}catch(e){report(e);}finally{setBusy(false);}}
 const output=outputs.find(o=>o.name===selected), edit=edits.find(o=>o.name===selected), internal=!!output&&(output.name.startsWith("eDP")||output.name.startsWith("LVDS")||output.name.startsWith("DSI"));
 return <><p className="section-caption">Select a display to change its resolution, scale, rotation, and position.</p><div className="display-arrangement" aria-label="Connected displays">{outputs.map((o,i)=><button key={o.name} className={`display-tile${selected===o.name?" selected":""}`} aria-pressed={selected===o.name} onClick={()=>select(o.name)}><span className="display-glass"><b>{i+1}</b><small>{o.name}</small></span><span>{o.description || o.name}</span></button>)}{!outputs.length&&<p>No configurable displays found.</p>}</div>
 {edit&&output&&<div className="settings-card"><div className="settings-row"><strong>{output.description || output.name}</strong><Toggle label="Enable display" checked={edit.enabled} disabled={busy||!!trial} onChange={enabled=>update({enabled})}/></div><div className="settings-row"><label htmlFor="resolution">Resolution & refresh rate</label><select id="resolution" disabled={busy||!!trial} value={`${edit.width}:${edit.height}:${edit.refresh}`} onChange={e=>{const[width,height,refresh]=e.target.value.split(':').map(Number);update({width:width!,height:height!,refresh:refresh!});}}>{output.modes.map(m=><option key={`${m.width}:${m.height}:${m.refresh}`} value={`${m.width}:${m.height}:${m.refresh}`}>{m.width} × {m.height} · {(m.refresh/1000).toFixed(2)} Hz{m.preferred?" (recommended)":""}</option>)}</select></div><div className="settings-row"><label htmlFor="display-scale">Scale</label><select id="display-scale" value={edit.scale} disabled={busy||!!trial} onChange={e=>update({scale:Number(e.target.value)})}>{[...new Set([1,1.25,1.5,1.75,2,2.5,3,edit.scale])].sort((a,b)=>a-b).map(v=><option key={v} value={v}>{Math.round(v*100)}%</option>)}</select></div><div className="settings-row"><label htmlFor="rotation">Rotation</label><select id="rotation" value={edit.transform} disabled={busy||!!trial} onChange={e=>update({transform:Number(e.target.value)})}>{[0,1,2,3].map(v=><option key={v} value={v}>{v*90}°</option>)}{edit.transform>3&&<option value={edit.transform}>Flipped</option>}</select></div><div className="settings-row"><span>Position in desktop</span><div className="display-position"><label>X<input type="number" aria-label="Display X position" min="-32768" max="32768" value={edit.x} disabled={busy||!!trial} onChange={e=>update({x:Number(e.target.value)})}/></label><label>Y<input type="number" aria-label="Display Y position" min="-32768" max="32768" value={edit.y} disabled={busy||!!trial} onChange={e=>update({y:Number(e.target.value)})}/></label></div></div></div>}
 <div className="settings-card">{internal?<SystemSlider name="brightness" label="Built-in display brightness" value={settings.brightness} report={report}/>:<div className="monitor-brightness"><label htmlFor="monitor-brightness">Monitor brightness</label><input id="monitor-brightness" type="range" min="0" max="100" value={monitorBrightness??50} disabled={!output||!output.enabled||monitorBrightness===null||brightnessBusy} onChange={e=>setExternalBrightness(Number(e.target.value))}/><span>{!output?"Select a display":!output.enabled?"Enable this display to adjust brightness":brightnessBusy?"Updating…":monitorBrightness===null?"DDC/CI brightness unavailable":""}</span></div>}</div><div className="settings-actions"><button disabled={busy||!!trial} onClick={()=>void load().catch(report)}>Detect displays</button><button className="primary" disabled={busy||!!trial||!outputs.length} onClick={()=>void apply()}>{busy?"Applying…":"Apply changes"}</button></div>{error&&<p role="alert" className="settings-error">{error}</p>}{trial&&<div className="device-dialog-scrim"><section role="dialog" aria-modal="true" aria-label="Keep display settings" className="device-dialog"><h3>Keep these display settings?</h3><p>Reverting automatically in {seconds} seconds.</p><div className="settings-actions"><button disabled={busy} onClick={()=>void decide(false)}>Revert</button><button className="primary" disabled={busy} onClick={()=>void decide(true)}>Keep changes</button></div></section></div>}</>;
}
export function Wireless({kind}:{kind:"wifi"|"bluetooth"}) {
 const {settings,setSettings}=useSystemSettings(),[networks,setNetworks]=useState<WifiNetwork[]>([]),[devices,setDevices]=useState<BluetoothDevice[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[network,setNetwork]=useState<WifiNetwork|null>(null),[password,setPassword]=useState("");
 const name=kind==="wifi"?"Wi-Fi":"Bluetooth", value=settings[kind];
 const report=(e:unknown)=>setError(errorMessage(e));
 async function load(){if(kind==="wifi")setNetworks(await request({method:"settings.wifi_networks"})??[]);else setDevices(await request({method:"settings.bluetooth_devices"})??[]);}
 useEffect(()=>{void load().catch(report);},[kind]);
 async function toggle(enabled:boolean){setBusy(true);setError("");try{await request({method:kind==="wifi"?"settings.set_wifi":"settings.set_bluetooth",params:{enabled}});setSettings(await request({method:"settings.get"}));}catch(e){report(e);}finally{setBusy(false);}}
 async function scan(){setBusy(true);setError("");try{if(kind==="bluetooth")await request({method:"settings.bluetooth_scan"});await load();}catch(e){report(e);}finally{setBusy(false);}}
 async function connect(){if(!network)return;setBusy(true);setError("");try{await request({method:"settings.wifi_connect",params:{bssid:network.bssid,device:network.device,password}});setNetwork(null);setPassword("");await load();}catch(e){setPassword("");report(e);}finally{setBusy(false);}}
 async function deviceAction(device:BluetoothDevice){setBusy(true);setError("");try{await request({method:"settings.bluetooth_action",params:{path:device.path,action:device.connected?"disconnect":device.paired?"connect":"pair"}});await load();}catch(e){report(e);}finally{setBusy(false);}}
 return <><div className="settings-card"><div className="settings-row"><div><strong>{name}</strong><small className="row-detail">{value===null?"No adapter available":value?"On":"Off"}</small></div><Toggle id={kind} label={name} checked={value===true} disabled={busy||value===null} onChange={v=>void toggle(v)}/></div></div><div className="pane-heading"><h3>{kind==="wifi"?"Available networks":"Nearby devices"}</h3><button disabled={busy||value!==true} onClick={()=>void scan()}>{busy?"Working…":"Scan again"}</button></div><div className="settings-card">{kind==="wifi"?networks.map(n=><div key={`${n.device}:${n.bssid}`} className="settings-row"><span className="device-symbol" aria-hidden="true">⌁</span><div className="device-name"><strong>{n.ssid}</strong><small className="row-detail">{n.connected?"Connected · ":""}{n.signal}% signal · {n.security||"Open network"}</small></div><button disabled={busy||value!==true||n.connected} onClick={()=>{setNetwork(n);setPassword("");}}>{n.connected?"Connected":"Connect"}</button></div>):devices.map(d=><div key={d.path} className="settings-row"><span className="device-symbol" aria-hidden="true">ᛒ</span><div className="device-name"><strong>{d.name}</strong><small className="row-detail">{d.connected?"Connected":d.paired?"Paired":"Not paired"}</small></div><button disabled={busy||value!==true} onClick={()=>void deviceAction(d)}>{d.connected?"Disconnect":d.paired?"Connect":"Pair"}</button></div>)}{!(kind==="wifi"?networks:devices).length&&<p className="device-empty">{value===true?"No devices found. Try scanning again.":`Turn on ${name} to discover ${kind==="wifi"?"networks":"devices"}.`}</p>}</div>{error&&<p className="settings-error" role="alert">{error}</p>}{network&&<div className="device-dialog-scrim"><form className="device-dialog" role="dialog" aria-modal="true" aria-label="Connect to Wi-Fi" onSubmit={e=>{e.preventDefault();void connect();}}><h3>Join {network.ssid}</h3>{network.security&&network.security!=="--"&&<label>Password<input type="password" aria-label="Wi-Fi password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus/></label>}<div className="settings-actions"><button type="button" disabled={busy} onClick={()=>{setNetwork(null);setPassword("");}}>Cancel</button><button className="primary" disabled={busy} type="submit">{busy?"Connecting…":"Join"}</button></div></form></div>}</>;
}
export function Sharing() {
 const [enabled,setEnabled]=useState<Record<string,boolean>>({});
 const services=[['File Sharing','Share selected folders with other computers.'],['Screen Sharing','Allow someone to view or control your screen.'],['Media Sharing','Share music and video libraries on your network.'],['Remote Login','Access this computer through a secure terminal.'],['Internet Sharing','Share your network connection with another device.']];
 return <><p className="section-caption">Prototype · These preferences preview the interface and do not start sharing services.</p><div className="settings-card">{services.map(([name,description])=><div className="settings-row" key={name}><div><strong>{name}</strong><small className="row-detail">{description}</small></div><Toggle label={name} checked={!!enabled[name!]} onChange={value=>setEnabled(old=>({...old,[name!]:value}))}/></div>)}</div><div className="settings-card"><div className="settings-row"><label htmlFor="computer-name">Computer name</label><input id="computer-name" defaultValue="Meridian"/></div><div className="settings-row"><span>Shared folders</span><button disabled>Add folder…</button></div><p className="section-caption card-caption">Folder selection and access permissions will be connected when sharing is implemented.</p></div></>;
}
